version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: vibelink-backend
    environment:
      DATABASE_URL: postgresql://vibelink:vibelink@postgres:5432/vibelink?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_MASTER_KEY: masterKey
      NODE_ENV: production
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/main"

  postgres:
    image: postgres:16-alpine
    container_name: vibelink-postgres
    environment:
      POSTGRES_USER: vibelink
      POSTGRES_PASSWORD: vibelink
      POSTGRES_DB: vibelink
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vibelink']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vibelink-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: vibelink-meilisearch
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_ENV: production
    ports:
      - '7700:7700'
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
